//**********************************************************************`
//* This is an include file generated by Message Compiler.             *`
//*                                                                    *`
//* Copyright (c) Microsoft Corporation. All Rights Reserved.          *`
//**********************************************************************`
#pragma once

//*****************************************************************************
//
// Notes on the ETW event code generated by MC:
//
// - Structures and arrays of structures are treated as an opaque binary blob.
//   The caller is responsible for packing the data for the structure into a
//   single region of memory, with no padding between values. The macro will
//   have an extra parameter for the length of the blob.
// - Arrays of nul-terminated strings must be packed by the caller into a
//   single binary blob containing the correct number of strings, with a nul
//   after each string. The size of the blob is specified in characters, and
//   includes the final nul.
// - If a SID is provided, its length will be determined by calling
//   GetLengthSid.
// - Arrays of SID are treated as a single binary blob. The caller is
//   responsible for packing the SID values into a single region of memory with
//   no padding.
// - The length attribute on the data element in the manifest is significant
//   for values with intype win:UnicodeString, win:AnsiString, or win:Binary.
//   The length attribute must be specified for win:Binary, and is optional for
//   win:UnicodeString and win:AnsiString (if no length is given, the strings
//   are assumed to be nul-terminated). For win:UnicodeString, the length is
//   measured in characters, not bytes.
// - For an array of win:UnicodeString, win:AnsiString, or win:Binary, the
//   length attribute applies to every value in the array, so every value in
//   the array must have the same length. The values in the array are provided
//   to the macro via a single pointer -- the caller is responsible for packing
//   all of the values into a single region of memory with no padding between
//   values.
// - Values of type win:CountedUnicodeString, win:CountedAnsiString, and
//   win:CountedBinary can be generated and collected on Vista or later.
//   However, they may not decode properly without the Windows 10 2018 Fall
//   Update.
// - Arrays of type win:CountedUnicodeString, win:CountedAnsiString, and
//   win:CountedBinary must be packed by the caller into a single region of
//   memory. The format for each item is a UINT16 byte-count followed by that
//   many bytes of data. When providing the array to the generated macro, you
//   must provide the total size of the packed array data, including the UINT16
//   sizes for each item. In the case of win:CountedUnicodeString, the data
//   size is specified in WCHAR (16-bit) units. In the case of
//   win:CountedAnsiString and win:CountedBinary, the data size is specified in
//   bytes.
//
//*****************************************************************************

#include <wmistr.h>
#include <evntrace.h>
#include <evntprov.h>

#if !defined(ETW_INLINE)
#define ETW_INLINE DECLSPEC_NOINLINE __inline
#endif

#if defined(__cplusplus)
extern "C" {
#endif

//
// MCGEN_DISABLE_PROVIDER_CODE_GENERATION macro:
// Define this macro to have the compiler skip the generated functions in this
// header.
//
#ifndef MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//
// MCGEN_USE_KERNEL_MODE_APIS macro:
// Controls whether the generated code uses kernel-mode or user-mode APIs.
// - Set to 0 to use Windows user-mode APIs such as EventRegister.
// - Set to 1 to use Windows kernel-mode APIs such as EtwRegister.
// Default is based on whether the _ETW_KM_ macro is defined (i.e. by wdm.h).
// Note that the APIs can also be overridden directly, e.g. by setting the
// MCGEN_EVENTWRITETRANSFER or MCGEN_EVENTREGISTER macros.
//
#ifndef MCGEN_USE_KERNEL_MODE_APIS
  #ifdef _ETW_KM_
    #define MCGEN_USE_KERNEL_MODE_APIS 1
  #else
    #define MCGEN_USE_KERNEL_MODE_APIS 0
  #endif
#endif // MCGEN_USE_KERNEL_MODE_APIS

//
// MCGEN_HAVE_EVENTSETINFORMATION macro:
// Controls how McGenEventSetInformation uses the EventSetInformation API.
// - Set to 0 to disable the use of EventSetInformation
//   (McGenEventSetInformation will always return an error).
// - Set to 1 to directly invoke MCGEN_EVENTSETINFORMATION.
// - Set to 2 to to locate EventSetInformation at runtime via GetProcAddress
//   (user-mode) or MmGetSystemRoutineAddress (kernel-mode).
// Default is determined as follows:
// - If MCGEN_EVENTSETINFORMATION has been customized, set to 1
//   (i.e. use MCGEN_EVENTSETINFORMATION).
// - Else if the target OS version has EventSetInformation, set to 1
//   (i.e. use MCGEN_EVENTSETINFORMATION).
// - Else set to 2 (i.e. try to dynamically locate EventSetInformation).
// Note that an McGenEventSetInformation function will only be generated if one
// or more provider in a manifest has provider traits.
//
#ifndef MCGEN_HAVE_EVENTSETINFORMATION
  #ifdef MCGEN_EVENTSETINFORMATION             // if MCGEN_EVENTSETINFORMATION has been customized,
    #define MCGEN_HAVE_EVENTSETINFORMATION   1 //   directly invoke MCGEN_EVENTSETINFORMATION(...).
  #elif MCGEN_USE_KERNEL_MODE_APIS             // else if using kernel-mode APIs,
    #if NTDDI_VERSION >= 0x06040000            //   if target OS is Windows 10 or later,
      #define MCGEN_HAVE_EVENTSETINFORMATION 1 //     directly invoke MCGEN_EVENTSETINFORMATION(...).
    #else                                      //   else
      #define MCGEN_HAVE_EVENTSETINFORMATION 2 //     find "EtwSetInformation" via MmGetSystemRoutineAddress.
    #endif                                     // else (using user-mode APIs)
  #else                                        //   if target OS and SDK is Windows 8 or later,
    #if WINVER >= 0x0602 && defined(EVENT_FILTER_TYPE_SCHEMATIZED)
      #define MCGEN_HAVE_EVENTSETINFORMATION 1 //     directly invoke MCGEN_EVENTSETINFORMATION(...).
    #else                                      //   else
      #define MCGEN_HAVE_EVENTSETINFORMATION 2 //     find "EventSetInformation" via GetModuleHandleExW/GetProcAddress.
    #endif
  #endif
#endif // MCGEN_HAVE_EVENTSETINFORMATION

//
// MCGEN_EVENTWRITETRANSFER macro:
// Override to use a custom API.
//
#ifndef MCGEN_EVENTWRITETRANSFER
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define MCGEN_EVENTWRITETRANSFER   EtwWriteTransfer
  #else
    #define MCGEN_EVENTWRITETRANSFER   EventWriteTransfer
  #endif
#endif // MCGEN_EVENTWRITETRANSFER

//
// MCGEN_EVENTREGISTER macro:
// Override to use a custom API.
//
#ifndef MCGEN_EVENTREGISTER
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define MCGEN_EVENTREGISTER        EtwRegister
  #else
    #define MCGEN_EVENTREGISTER        EventRegister
  #endif
#endif // MCGEN_EVENTREGISTER

//
// MCGEN_EVENTSETINFORMATION macro:
// Override to use a custom API.
// (McGenEventSetInformation also affected by MCGEN_HAVE_EVENTSETINFORMATION.)
//
#ifndef MCGEN_EVENTSETINFORMATION
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define MCGEN_EVENTSETINFORMATION  EtwSetInformation
  #else
    #define MCGEN_EVENTSETINFORMATION  EventSetInformation
  #endif
#endif // MCGEN_EVENTSETINFORMATION

//
// MCGEN_EVENTUNREGISTER macro:
// Override to use a custom API.
//
#ifndef MCGEN_EVENTUNREGISTER
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define MCGEN_EVENTUNREGISTER      EtwUnregister
  #else
    #define MCGEN_EVENTUNREGISTER      EventUnregister
  #endif
#endif // MCGEN_EVENTUNREGISTER

//
// MCGEN_PENABLECALLBACK macro:
// Override to use a custom function pointer type.
// (Should match the type used by MCGEN_EVENTREGISTER.)
//
#ifndef MCGEN_PENABLECALLBACK
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define MCGEN_PENABLECALLBACK      PETWENABLECALLBACK
  #else
    #define MCGEN_PENABLECALLBACK      PENABLECALLBACK
  #endif
#endif // MCGEN_PENABLECALLBACK

//
// MCGEN_GETLENGTHSID macro:
// Override to use a custom API.
//
#ifndef MCGEN_GETLENGTHSID
  #if MCGEN_USE_KERNEL_MODE_APIS
    #define MCGEN_GETLENGTHSID(p)      RtlLengthSid((PSID)(p))
  #else
    #define MCGEN_GETLENGTHSID(p)      GetLengthSid((PSID)(p))
  #endif
#endif // MCGEN_GETLENGTHSID

//
// MCGEN_EVENT_ENABLED macro:
// Controls how the EventWrite[EventName] macros determine whether an event is
// enabled. The default behavior is for EventWrite[EventName] to use the
// EventEnabled[EventName] macros.
//
#ifndef MCGEN_EVENT_ENABLED
#define MCGEN_EVENT_ENABLED(EventName) EventEnabled##EventName()
#endif

//
// MCGEN_EVENT_BIT_SET macro:
// Implements testing a bit in an array of ULONG, optimized for CPU type.
//
#ifndef MCGEN_EVENT_BIT_SET
#  if defined(_M_IX86) || defined(_M_X64)
#    define MCGEN_EVENT_BIT_SET(EnableBits, BitPosition) ((((const unsigned char*)EnableBits)[BitPosition >> 3] & (1u << (BitPosition & 7))) != 0)
#  else
#    define MCGEN_EVENT_BIT_SET(EnableBits, BitPosition) ((EnableBits[BitPosition >> 5] & (1u << (BitPosition & 31))) != 0)
#  endif
#endif // MCGEN_EVENT_BIT_SET

//
// MCGEN_ENABLE_CHECK macro:
// Determines whether the specified event would be considered as enabled
// based on the state of the specified context. Slightly faster than calling
// McGenEventEnabled directly.
//
#ifndef MCGEN_ENABLE_CHECK
#define MCGEN_ENABLE_CHECK(Context, Descriptor) (Context.IsEnabled && McGenEventEnabled(&Context, &Descriptor))
#endif

#if !defined(MCGEN_TRACE_CONTEXT_DEF)
#define MCGEN_TRACE_CONTEXT_DEF
typedef struct _MCGEN_TRACE_CONTEXT
{
    TRACEHANDLE            RegistrationHandle;
    TRACEHANDLE            Logger;      // Used as pointer to provider traits.
    ULONGLONG              MatchAnyKeyword;
    ULONGLONG              MatchAllKeyword;
    ULONG                  Flags;
    ULONG                  IsEnabled;
    UCHAR                  Level;
    UCHAR                  Reserve;
    USHORT                 EnableBitsCount;
    PULONG                 EnableBitMask;
    const ULONGLONG*       EnableKeyWords;
    const UCHAR*           EnableLevel;
} MCGEN_TRACE_CONTEXT, *PMCGEN_TRACE_CONTEXT;
#endif // MCGEN_TRACE_CONTEXT_DEF

#if !defined(MCGEN_LEVEL_KEYWORD_ENABLED_DEF)
#define MCGEN_LEVEL_KEYWORD_ENABLED_DEF
//
// Determines whether an event with a given Level and Keyword would be
// considered as enabled based on the state of the specified context.
// Note that you may want to use MCGEN_ENABLE_CHECK instead of calling this
// function directly.
//
FORCEINLINE
BOOLEAN
McGenLevelKeywordEnabled(
    _In_ PMCGEN_TRACE_CONTEXT EnableInfo,
    _In_ UCHAR Level,
    _In_ ULONGLONG Keyword
    )
{
    //
    // Check if the event Level is lower than the level at which
    // the channel is enabled.
    // If the event Level is 0 or the channel is enabled at level 0,
    // all levels are enabled.
    //

    if ((Level <= EnableInfo->Level) || // This also covers the case of Level == 0.
        (EnableInfo->Level == 0)) {

        //
        // Check if Keyword is enabled
        //

        if ((Keyword == (ULONGLONG)0) ||
            ((Keyword & EnableInfo->MatchAnyKeyword) &&
             ((Keyword & EnableInfo->MatchAllKeyword) == EnableInfo->MatchAllKeyword))) {
            return TRUE;
        }
    }

    return FALSE;
}
#endif // MCGEN_LEVEL_KEYWORD_ENABLED_DEF

#if !defined(MCGEN_EVENT_ENABLED_DEF)
#define MCGEN_EVENT_ENABLED_DEF
//
// Determines whether the specified event would be considered as enabled based
// on the state of the specified context. Note that you may want to use
// MCGEN_ENABLE_CHECK instead of calling this function directly.
//
FORCEINLINE
BOOLEAN
McGenEventEnabled(
    _In_ PMCGEN_TRACE_CONTEXT EnableInfo,
    _In_ PCEVENT_DESCRIPTOR EventDescriptor
    )
{
    return McGenLevelKeywordEnabled(EnableInfo, EventDescriptor->Level, EventDescriptor->Keyword);
}
#endif // MCGEN_EVENT_ENABLED_DEF

#if !defined(MCGEN_CONTROL_CALLBACK)
#define MCGEN_CONTROL_CALLBACK

DECLSPEC_NOINLINE __inline
VOID
__stdcall
McGenControlCallbackV2(
    _In_ LPCGUID SourceId,
    _In_ ULONG ControlCode,
    _In_ UCHAR Level,
    _In_ ULONGLONG MatchAnyKeyword,
    _In_ ULONGLONG MatchAllKeyword,
    _In_opt_ PEVENT_FILTER_DESCRIPTOR FilterData,
    _Inout_opt_ PVOID CallbackContext
    )
/*++

Routine Description:

    This is the notification callback for Windows Vista and later.

Arguments:

    SourceId - The GUID that identifies the session that enabled the provider.

    ControlCode - The parameter indicates whether the provider
                  is being enabled or disabled.

    Level - The level at which the event is enabled.

    MatchAnyKeyword - The bitmask of keywords that the provider uses to
                      determine the category of events that it writes.

    MatchAllKeyword - This bitmask additionally restricts the category
                      of events that the provider writes.

    FilterData - The provider-defined data.

    CallbackContext - The context of the callback that is defined when the provider
                      called EtwRegister to register itself.

Remarks:

    ETW calls this function to notify provider of enable/disable

--*/
{
    PMCGEN_TRACE_CONTEXT Ctx = (PMCGEN_TRACE_CONTEXT)CallbackContext;
    ULONG Ix;
#ifndef MCGEN_PRIVATE_ENABLE_CALLBACK_V2
    UNREFERENCED_PARAMETER(SourceId);
    UNREFERENCED_PARAMETER(FilterData);
#endif

    if (Ctx == NULL) {
        return;
    }

    switch (ControlCode) {

        case EVENT_CONTROL_CODE_ENABLE_PROVIDER:
            Ctx->Level = Level;
            Ctx->MatchAnyKeyword = MatchAnyKeyword;
            Ctx->MatchAllKeyword = MatchAllKeyword;
            Ctx->IsEnabled = EVENT_CONTROL_CODE_ENABLE_PROVIDER;

            for (Ix = 0; Ix < Ctx->EnableBitsCount; Ix += 1) {
                if (McGenLevelKeywordEnabled(Ctx, Ctx->EnableLevel[Ix], Ctx->EnableKeyWords[Ix]) != FALSE) {
                    Ctx->EnableBitMask[Ix >> 5] |= (1 << (Ix % 32));
                } else {
                    Ctx->EnableBitMask[Ix >> 5] &= ~(1 << (Ix % 32));
                }
            }
            break;

        case EVENT_CONTROL_CODE_DISABLE_PROVIDER:
            Ctx->IsEnabled = EVENT_CONTROL_CODE_DISABLE_PROVIDER;
            Ctx->Level = 0;
            Ctx->MatchAnyKeyword = 0;
            Ctx->MatchAllKeyword = 0;
            if (Ctx->EnableBitsCount > 0) {
                RtlZeroMemory(Ctx->EnableBitMask, (((Ctx->EnableBitsCount - 1) / 32) + 1) * sizeof(ULONG));
            }
            break;

        default:
            break;
    }

#ifdef MCGEN_PRIVATE_ENABLE_CALLBACK_V2
    //
    // Call user defined callback
    //
    MCGEN_PRIVATE_ENABLE_CALLBACK_V2(
        SourceId,
        ControlCode,
        Level,
        MatchAnyKeyword,
        MatchAllKeyword,
        FilterData,
        CallbackContext
        );
#endif // MCGEN_PRIVATE_ENABLE_CALLBACK_V2

    return;
}

#endif // MCGEN_CONTROL_CALLBACK

#ifndef McGenEventWrite_def
#define McGenEventWrite_def
DECLSPEC_NOINLINE __inline
ULONG __stdcall
McGenEventWrite(
    _In_ PMCGEN_TRACE_CONTEXT Context,
    _In_ PCEVENT_DESCRIPTOR Descriptor,
    _In_opt_ LPCGUID ActivityId,
    _In_range_(1, 128) ULONG EventDataCount,
    _Inout_updates_(EventDataCount) EVENT_DATA_DESCRIPTOR* EventData
    )
{
    const USHORT UNALIGNED* Traits;

    // Some customized MCGEN_EVENTWRITETRANSFER macros might ignore ActivityId.
    UNREFERENCED_PARAMETER(ActivityId);

    Traits = (const USHORT UNALIGNED*)(UINT_PTR)Context->Logger;

    if (Traits == NULL) {
        EventData[0].Ptr = 0;
        EventData[0].Size = 0;
        EventData[0].Reserved = 0;
    } else {
        EventData[0].Ptr = (ULONG_PTR)Traits;
        EventData[0].Size = *Traits;
        EventData[0].Reserved = 2; // EVENT_DATA_DESCRIPTOR_TYPE_PROVIDER_METADATA
    }

    return MCGEN_EVENTWRITETRANSFER(
        Context->RegistrationHandle,
        Descriptor,
        ActivityId,
        NULL,
        EventDataCount,
        EventData);
}
#endif // McGenEventWrite_def

#ifndef McGenEventSetInformation_def
#define McGenEventSetInformation_def
_IRQL_requires_max_(PASSIVE_LEVEL)
DECLSPEC_NOINLINE __inline
ULONG __stdcall
McGenEventSetInformation(
    _In_ REGHANDLE RegHandle,
    _In_ EVENT_INFO_CLASS InformationClass,
    _In_opt_bytecount_(InformationLength) PVOID EventInformation,
    _In_ ULONG InformationLength
    )
/*++

Routine Description:

    This function invokes EventSetInformation to provide additional information
    to the ETW runtime.

    Note that the implementation of this function depends on the values of
    the MCGEN_HAVE_EVENTSETINFORMATION and MCGEN_EVENTSETINFORMATION macros.
    Depending on the values of these macros, this function may call
    EventSetInformation directly, may dynamically-load EventSetInformation
    via GetProcAddress, or may call a replacement function.

Arguments:

    RegHandle - Registration handle returned by EventRegister.

    InformationClass - Type of operation to be performed on the registration
                       object.

    EventInformation - The input buffer.

    InformationLength - Size of the input buffer.

--*/
{
    ULONG Error;

#if MCGEN_HAVE_EVENTSETINFORMATION == 1

#pragma warning(suppress: 6387) // It's ok for EventInformation to be null if InformationLength is 0.
    Error = MCGEN_EVENTSETINFORMATION(
        RegHandle,
        InformationClass,
        EventInformation,
        InformationLength);

#elif MCGEN_HAVE_EVENTSETINFORMATION == 2

#if MCGEN_USE_KERNEL_MODE_APIS
    typedef NTSTATUS(NTAPI* PFEtwSetInformation)(
        _In_ REGHANDLE regHandle,
        _In_ EVENT_INFO_CLASS informationClass,
        _In_opt_bytecount_(informationLength) PVOID eventInformation,
        _In_ ULONG informationLength);
    static UNICODE_STRING strEtwSetInformation = {
        sizeof(L"EtwSetInformation") - 2,
        sizeof(L"EtwSetInformation") - 2,
        L"EtwSetInformation"
    };
    PFEtwSetInformation pfEtwSetInformation;
#pragma warning(push)
#pragma warning(disable: 4055) // Allow the cast from a PVOID to a PFN
    pfEtwSetInformation = (PFEtwSetInformation)MmGetSystemRoutineAddress(&strEtwSetInformation);
#pragma warning(pop)
    if (pfEtwSetInformation)
    {
        Error = pfEtwSetInformation(
            RegHandle,
            InformationClass,
            EventInformation,
            InformationLength);
    }
    else
    {
        Error = STATUS_NOT_SUPPORTED;
    }
#else // !MCGEN_USE_KERNEL_MODE_APIS
    HMODULE hEventing;
    Error = ERROR_NOT_SUPPORTED;
    if (GetModuleHandleExW(0, L"api-ms-win-eventing-provider-l1-1-0", &hEventing) ||
        GetModuleHandleExW(0, L"advapi32", &hEventing))
    {
        typedef ULONG(WINAPI* PFEventSetInformation)(
            _In_ REGHANDLE regHandle,
            _In_ EVENT_INFO_CLASS informationClass,
            _In_opt_bytecount_(informationLength) PVOID eventInformation,
            _In_ ULONG informationLength);
        PFEventSetInformation pfEventSetInformation =
            (PFEventSetInformation)GetProcAddress(hEventing, "EventSetInformation");
        if (pfEventSetInformation)
        {
            Error = pfEventSetInformation(
                RegHandle,
                InformationClass,
                EventInformation,
                InformationLength);
        }

        FreeLibrary(hEventing);
    }
#endif // MCGEN_USE_KERNEL_MODE_APIS

#else // MCGEN_HAVE_EVENTSETINFORMATION == 0

    (void)RegHandle;
    (void)InformationClass;
    (void)EventInformation;
    (void)InformationLength;

  #if MCGEN_USE_KERNEL_MODE_APIS
    Error = STATUS_NOT_SUPPORTED;
  #else // !MCGEN_USE_KERNEL_MODE_APIS
    Error = ERROR_NOT_SUPPORTED;
  #endif // MCGEN_USE_KERNEL_MODE_APIS

#endif // MCGEN_HAVE_EVENTSETINFORMATION

    return Error;
}
#endif // McGenEventSetInformation_def

#ifndef McGenEventRegisterContext_def
#define McGenEventRegisterContext_def
#pragma warning(push)
#pragma warning(disable:6103)
_IRQL_requires_max_(PASSIVE_LEVEL)
DECLSPEC_NOINLINE __inline
ULONG __stdcall
McGenEventRegisterContext(
    _In_ LPCGUID ProviderId,
    _In_opt_ MCGEN_PENABLECALLBACK EnableCallback,
    _In_opt_ PVOID CallbackContext,
    _Inout_ MCGEN_TRACE_CONTEXT* Context
    )
/*++

Routine Description:

    This function registers the provider with ETW and registers provider
    traits. The EventRegister[ProviderName] macro will use this function
    instead of McGenEventRegister if the provider has traits to be registered.

Arguments:

    ProviderId - Provider ID to register with ETW.

    EnableCallback - Callback to be used.

    CallbackContext - Context for the callback.

    Context - Provider context.

Remarks:

    Should not be called if the provider is already registered (i.e. should not
    be called if Context->RegistrationHandle != 0). Repeatedly registering a
    provider is a bug and may indicate a race condition.

--*/
{
    ULONG Error;

    if (Context->RegistrationHandle != 0)
    {
#if MCGEN_USE_KERNEL_MODE_APIS
        Error = (ULONG)STATUS_INVALID_PARAMETER;
#else
        Error = ERROR_INVALID_PARAMETER;
#endif
    }
    else
    {
        Error = MCGEN_EVENTREGISTER(
            ProviderId,
            EnableCallback,
            CallbackContext,
            &Context->RegistrationHandle);
        if (Error == 0 && Context->Logger != 0)
        {
            (void)McGenEventSetInformation(
                Context->RegistrationHandle,
                (EVENT_INFO_CLASS)2, // EventProviderSetTraits
                (void*)Context->Logger,
                *(USHORT const UNALIGNED*)Context->Logger);
        }
    }

    return Error;
}
#pragma warning(pop)
#endif // McGenEventRegisterContext_def

#if !defined(McGenEventRegisterUnregister)
#define McGenEventRegisterUnregister

#pragma warning(push)
#pragma warning(disable:6103)
DECLSPEC_NOINLINE __inline
ULONG __stdcall
McGenEventRegister(
    _In_ LPCGUID ProviderId,
    _In_opt_ MCGEN_PENABLECALLBACK EnableCallback,
    _In_opt_ PVOID CallbackContext,
    _Inout_ PREGHANDLE RegHandle
    )
/*++

Routine Description:

    This function registers the provider with ETW.

Arguments:

    ProviderId - Provider ID to register with ETW.

    EnableCallback - Callback to be used.

    CallbackContext - Context for the callback.

    RegHandle - Pointer to registration handle.

Remarks:

    Should not be called if the provider is already registered (i.e. should not
    be called if *RegHandle != 0). Repeatedly registering a provider is a bug
    and may indicate a race condition. However, for compatibility with previous
    behavior, this function will return SUCCESS in this case.

--*/
{
    ULONG Error;

    if (*RegHandle != 0)
    {
        Error = 0; // ERROR_SUCCESS
    }
    else
    {
        Error = MCGEN_EVENTREGISTER(ProviderId, EnableCallback, CallbackContext, RegHandle);
    }

    return Error;
}
#pragma warning(pop)

DECLSPEC_NOINLINE __inline
ULONG __stdcall
McGenEventUnregister(_Inout_ PREGHANDLE RegHandle)
/*++

Routine Description:

    Unregister from ETW and set *RegHandle = 0.

Arguments:

    RegHandle - the pointer to the provider registration handle

Remarks:

    If provider has not been registered (i.e. if *RegHandle == 0),
    return SUCCESS. It is safe to call McGenEventUnregister even if the
    call to McGenEventRegister returned an error.

--*/
{
    ULONG Error;

    if(*RegHandle == 0)
    {
        Error = 0; // ERROR_SUCCESS
    }
    else
    {
        Error = MCGEN_EVENTUNREGISTER(*RegHandle);
        *RegHandle = (REGHANDLE)0;
    }

    return Error;
}

#endif // McGenEventRegisterUnregister

#endif // MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// Provider "ProviderName1{646E035B+4651-4D15-BC40-1897CC99E967)" event count 1
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Provider GUID = 646e035b-4651-4d15-bc40-1897cc99e967
EXTERN_C __declspec(selectany) const GUID ProviderSym1 = {0x646e035b, 0x4651, 0x4d15, {0xbc, 0x40, 0x18, 0x97, 0xcc, 0x99, 0xe9, 0x67}};

// Control GUID = 35919cde-6e0d-458f-84c1-d8930e18ac57
EXTERN_C __declspec(selectany) const GUID ProviderSym1_ControlGuid = {0x35919cde, 0x6e0d, 0x458f, {0x84, 0xc1, 0xd8, 0x93, 0x0e, 0x18, 0xac, 0x57}};

#ifndef ProviderSym1_Traits
#define ProviderSym1_Traits ( \
    "\x5C\x00" /* Total size of traits = 92 */ \
    "ProviderName1{646E035B+4651-4D15-BC40-1897CC99E967)\x00" /* Provider name */ \
    "\x13\x00\x01\xFD\xE8\xA0\x5F\xC9\x0A\xE1\x4E\x98\xDE\x73\xC6\x99\x12\xE6\xD1" /* Group guid */ \
    "\x13\x00\x02\x5B\x03\x6E\x64\x51\x46\x15\x4D\xBC\x40\x18\x97\xCC\x99\xE9\x67" /* Decode guid */ \
    )
#endif // ProviderSym1_Traits

//
// Event Descriptors
//
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR ProviderSym1_EVENT_0xa_0_c_0_0_0_0 = {0xa, 0x0, 0xc, 0x0, 0x0, 0x0, 0x0};
#define ProviderSym1_EVENT_0xa_0_c_0_0_0_0_value 0xa

//
// MCGEN_DISABLE_PROVIDER_CODE_GENERATION macro:
// Define this macro to have the compiler skip the generated functions in this
// header.
//
#ifndef MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//
// Event Enablement Bits
//
EXTERN_C __declspec(selectany) DECLSPEC_CACHEALIGN ULONG ProviderName1_646E035B_4651_4D15_BC40_1897CC99E967_EnableBits[1];
EXTERN_C __declspec(selectany) const ULONGLONG ProviderName1_646E035B_4651_4D15_BC40_1897CC99E967_Keywords[1] = {0x0};
EXTERN_C __declspec(selectany) const unsigned char ProviderName1_646E035B_4651_4D15_BC40_1897CC99E967_Levels[1] = {0};

//
// Provider context
//
EXTERN_C __declspec(selectany) MCGEN_TRACE_CONTEXT ProviderSym1_Context = {0, (ULONG_PTR)ProviderSym1_Traits, 0, 0, 0, 0, 0, 0, 1, ProviderName1_646E035B_4651_4D15_BC40_1897CC99E967_EnableBits, ProviderName1_646E035B_4651_4D15_BC40_1897CC99E967_Keywords, ProviderName1_646E035B_4651_4D15_BC40_1897CC99E967_Levels};

//
// Provider REGHANDLE
//
#define ProviderSym1_Handle (ProviderSym1_Context.RegistrationHandle)

//
// This macro is set to 0, indicating that the EventWrite[Name] macros do not
// have an Activity parameter. This is controlled by the -km and -um options.
//
#define ProviderSym1_EventWriteActivity 0

//
// Register with ETW using the control GUID specified in the manifest.
// Invoke this macro during module initialization (i.e. program startup,
// DLL process attach, or driver load) to initialize the provider.
// Note that if this function returns an error, the error means that
// will not work, but no action needs to be taken -- even if EventRegister
// returns an error, it is generally safe to use EventWrite and
// EventUnregister macros (they will be no-ops if EventRegister failed).
//
#ifndef EventRegister_ProviderSym1
#define EventRegister_ProviderSym1() McGenEventRegisterContext(&ProviderSym1_ControlGuid, McGenControlCallbackV2, &ProviderSym1_Context, &ProviderSym1_Context)
#endif

//
// Register with ETW using a specific control GUID (i.e. a GUID other than what
// is specified in the manifest). Advanced scenarios only.
//
#ifndef EventRegisterByGuid_ProviderSym1
#define EventRegisterByGuid_ProviderSym1(Guid) McGenEventRegisterContext(&(Guid), McGenControlCallbackV2, &ProviderSym1_Context, &ProviderSym1_Context)
#endif

//
// Unregister with ETW and close the provider.
// Invoke this macro during module shutdown (i.e. program exit, DLL process
// detach, or driver unload) to unregister the provider.
// Note that you MUST call EventUnregister before DLL or driver unload
// (not optional): failure to unregister a provider before DLL or driver unload
// will result in crashes.
//
#ifndef EventUnregister_ProviderSym1
#define EventUnregister_ProviderSym1() McGenEventUnregister(&ProviderSym1_Handle)
#endif

//
// Enablement check macro for ProviderSym1_EVENT_0xa_0_c_0_0_0_0
//
#define EventEnabledProviderSym1_EVENT_0xa_0_c_0_0_0_0() MCGEN_EVENT_BIT_SET(ProviderName1_646E035B_4651_4D15_BC40_1897CC99E967_EnableBits, 0)

//
// Event write macros for ProviderSym1_EVENT_0xa_0_c_0_0_0_0
//
#define EventWriteProviderSym1_EVENT_0xa_0_c_0_0_0_0() \
        MCGEN_EVENT_ENABLED(ProviderSym1_EVENT_0xa_0_c_0_0_0_0) \
        ? McTemplateU0(&ProviderSym1_Context, &ProviderSym1_EVENT_0xa_0_c_0_0_0_0) : 0
#define EventWriteProviderSym1_EVENT_0xa_0_c_0_0_0_0_AssumeEnabled() \
        McTemplateU0(&ProviderSym1_Context, &ProviderSym1_EVENT_0xa_0_c_0_0_0_0)

#endif // MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// Provider "ProviderName2.ABC5D6FFABF642C19174417F87643B00" event count 1
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Provider GUID = abc5d6ff-abf6-42c1-9174-417f87643b00
EXTERN_C __declspec(selectany) const GUID ProviderSym2 = {0xabc5d6ff, 0xabf6, 0x42c1, {0x91, 0x74, 0x41, 0x7f, 0x87, 0x64, 0x3b, 0x00}};

// Control GUID = 1be03d10-b7d7-4592-a26c-6929e038b328
EXTERN_C __declspec(selectany) const GUID ProviderSym2_ControlGuid = {0x1be03d10, 0xb7d7, 0x4592, {0xa2, 0x6c, 0x69, 0x29, 0xe0, 0x38, 0xb3, 0x28}};

#ifndef ProviderSym2_Traits
#define ProviderSym2_Traits ( \
    "\x29\x00" /* Total size of traits = 41 */ \
    "\x00" /* Provider name omitted */ \
    "\x13\x00\x01\xFD\xE8\xA0\x5F\xC9\x0A\xE1\x4E\x98\xDE\x73\xC6\x99\x12\xE6\xD1" /* Group guid */ \
    "\x13\x00\x02\xFF\xD6\xC5\xAB\xF6\xAB\xC1\x42\x91\x74\x41\x7F\x87\x64\x3B\x00" /* Decode guid */ \
    )
#endif // ProviderSym2_Traits

//
// Event Descriptors
//
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR ProviderSym2_EVENT_0x14_0_c_0_0_0_0 = {0x14, 0x0, 0xc, 0x0, 0x0, 0x0, 0x0};
#define ProviderSym2_EVENT_0x14_0_c_0_0_0_0_value 0x14

//
// MCGEN_DISABLE_PROVIDER_CODE_GENERATION macro:
// Define this macro to have the compiler skip the generated functions in this
// header.
//
#ifndef MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//
// Event Enablement Bits
//
EXTERN_C __declspec(selectany) DECLSPEC_CACHEALIGN ULONG ProviderName2_ABC5D6FFABF642C19174417F87643B00EnableBits[1];
EXTERN_C __declspec(selectany) const ULONGLONG ProviderName2_ABC5D6FFABF642C19174417F87643B00Keywords[1] = {0x0};
EXTERN_C __declspec(selectany) const unsigned char ProviderName2_ABC5D6FFABF642C19174417F87643B00Levels[1] = {0};

//
// Provider context
//
EXTERN_C __declspec(selectany) MCGEN_TRACE_CONTEXT ProviderSym2_Context = {0, (ULONG_PTR)ProviderSym2_Traits, 0, 0, 0, 0, 0, 0, 1, ProviderName2_ABC5D6FFABF642C19174417F87643B00EnableBits, ProviderName2_ABC5D6FFABF642C19174417F87643B00Keywords, ProviderName2_ABC5D6FFABF642C19174417F87643B00Levels};

//
// Provider REGHANDLE
//
#define ProviderSym2_Handle (ProviderSym2_Context.RegistrationHandle)

//
// This macro is set to 0, indicating that the EventWrite[Name] macros do not
// have an Activity parameter. This is controlled by the -km and -um options.
//
#define ProviderSym2_EventWriteActivity 0

//
// Register with ETW using the control GUID specified in the manifest.
// Invoke this macro during module initialization (i.e. program startup,
// DLL process attach, or driver load) to initialize the provider.
// Note that if this function returns an error, the error means that
// will not work, but no action needs to be taken -- even if EventRegister
// returns an error, it is generally safe to use EventWrite and
// EventUnregister macros (they will be no-ops if EventRegister failed).
//
#ifndef EventRegister_ProviderSym2
#define EventRegister_ProviderSym2() McGenEventRegisterContext(&ProviderSym2_ControlGuid, McGenControlCallbackV2, &ProviderSym2_Context, &ProviderSym2_Context)
#endif

//
// Register with ETW using a specific control GUID (i.e. a GUID other than what
// is specified in the manifest). Advanced scenarios only.
//
#ifndef EventRegisterByGuid_ProviderSym2
#define EventRegisterByGuid_ProviderSym2(Guid) McGenEventRegisterContext(&(Guid), McGenControlCallbackV2, &ProviderSym2_Context, &ProviderSym2_Context)
#endif

//
// Unregister with ETW and close the provider.
// Invoke this macro during module shutdown (i.e. program exit, DLL process
// detach, or driver unload) to unregister the provider.
// Note that you MUST call EventUnregister before DLL or driver unload
// (not optional): failure to unregister a provider before DLL or driver unload
// will result in crashes.
//
#ifndef EventUnregister_ProviderSym2
#define EventUnregister_ProviderSym2() McGenEventUnregister(&ProviderSym2_Handle)
#endif

//
// Enablement check macro for ProviderSym2_EVENT_0x14_0_c_0_0_0_0
//
#define EventEnabledProviderSym2_EVENT_0x14_0_c_0_0_0_0() MCGEN_EVENT_BIT_SET(ProviderName2_ABC5D6FFABF642C19174417F87643B00EnableBits, 0)

//
// Event write macros for ProviderSym2_EVENT_0x14_0_c_0_0_0_0
//
#define EventWriteProviderSym2_EVENT_0x14_0_c_0_0_0_0() \
        MCGEN_EVENT_ENABLED(ProviderSym2_EVENT_0x14_0_c_0_0_0_0) \
        ? McTemplateU0(&ProviderSym2_Context, &ProviderSym2_EVENT_0x14_0_c_0_0_0_0) : 0
#define EventWriteProviderSym2_EVENT_0x14_0_c_0_0_0_0_AssumeEnabled() \
        McTemplateU0(&ProviderSym2_Context, &ProviderSym2_EVENT_0x14_0_c_0_0_0_0)

#endif // MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// Provider "ProviderName3.418DACB3DA4B47FD851803EA8A6552E9" event count 1
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Provider GUID = 418dacb3-da4b-47fd-8518-03ea8a6552e9
EXTERN_C __declspec(selectany) const GUID ProviderSym3 = {0x418dacb3, 0xda4b, 0x47fd, {0x85, 0x18, 0x03, 0xea, 0x8a, 0x65, 0x52, 0xe9}};

// Control GUID = a97bb888-deb4-40b7-9c46-52c21f4fd0de
EXTERN_C __declspec(selectany) const GUID ProviderSym3_ControlGuid = {0xa97bb888, 0xdeb4, 0x40b7, {0x9c, 0x46, 0x52, 0xc2, 0x1f, 0x4f, 0xd0, 0xde}};

#ifndef ProviderSym3_Traits
#define ProviderSym3_Traits ( \
    "\x44\x00" /* Total size of traits = 68 */ \
    "ProviderName3.418DACB3DA4B47FD851803EA8A6552E9\x00" /* Provider name */ \
    "\x13\x00\x02\xB3\xAC\x8D\x41\x4B\xDA\xFD\x47\x85\x18\x03\xEA\x8A\x65\x52\xE9" /* Decode guid */ \
    )
#endif // ProviderSym3_Traits

//
// Event Descriptors
//
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR ProviderSym3_EVENT_0x1e_0_c_0_0_0_0 = {0x1e, 0x0, 0xc, 0x0, 0x0, 0x0, 0x0};
#define ProviderSym3_EVENT_0x1e_0_c_0_0_0_0_value 0x1e

//
// MCGEN_DISABLE_PROVIDER_CODE_GENERATION macro:
// Define this macro to have the compiler skip the generated functions in this
// header.
//
#ifndef MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//
// Event Enablement Bits
//
EXTERN_C __declspec(selectany) DECLSPEC_CACHEALIGN ULONG ProviderName3_418DACB3DA4B47FD851803EA8A6552E9EnableBits[1];
EXTERN_C __declspec(selectany) const ULONGLONG ProviderName3_418DACB3DA4B47FD851803EA8A6552E9Keywords[1] = {0x0};
EXTERN_C __declspec(selectany) const unsigned char ProviderName3_418DACB3DA4B47FD851803EA8A6552E9Levels[1] = {0};

//
// Provider context
//
EXTERN_C __declspec(selectany) MCGEN_TRACE_CONTEXT ProviderSym3_Context = {0, (ULONG_PTR)ProviderSym3_Traits, 0, 0, 0, 0, 0, 0, 1, ProviderName3_418DACB3DA4B47FD851803EA8A6552E9EnableBits, ProviderName3_418DACB3DA4B47FD851803EA8A6552E9Keywords, ProviderName3_418DACB3DA4B47FD851803EA8A6552E9Levels};

//
// Provider REGHANDLE
//
#define ProviderSym3_Handle (ProviderSym3_Context.RegistrationHandle)

//
// This macro is set to 0, indicating that the EventWrite[Name] macros do not
// have an Activity parameter. This is controlled by the -km and -um options.
//
#define ProviderSym3_EventWriteActivity 0

//
// Register with ETW using the control GUID specified in the manifest.
// Invoke this macro during module initialization (i.e. program startup,
// DLL process attach, or driver load) to initialize the provider.
// Note that if this function returns an error, the error means that
// will not work, but no action needs to be taken -- even if EventRegister
// returns an error, it is generally safe to use EventWrite and
// EventUnregister macros (they will be no-ops if EventRegister failed).
//
#ifndef EventRegister_ProviderSym3
#define EventRegister_ProviderSym3() McGenEventRegisterContext(&ProviderSym3_ControlGuid, McGenControlCallbackV2, &ProviderSym3_Context, &ProviderSym3_Context)
#endif

//
// Register with ETW using a specific control GUID (i.e. a GUID other than what
// is specified in the manifest). Advanced scenarios only.
//
#ifndef EventRegisterByGuid_ProviderSym3
#define EventRegisterByGuid_ProviderSym3(Guid) McGenEventRegisterContext(&(Guid), McGenControlCallbackV2, &ProviderSym3_Context, &ProviderSym3_Context)
#endif

//
// Unregister with ETW and close the provider.
// Invoke this macro during module shutdown (i.e. program exit, DLL process
// detach, or driver unload) to unregister the provider.
// Note that you MUST call EventUnregister before DLL or driver unload
// (not optional): failure to unregister a provider before DLL or driver unload
// will result in crashes.
//
#ifndef EventUnregister_ProviderSym3
#define EventUnregister_ProviderSym3() McGenEventUnregister(&ProviderSym3_Handle)
#endif

//
// Enablement check macro for ProviderSym3_EVENT_0x1e_0_c_0_0_0_0
//
#define EventEnabledProviderSym3_EVENT_0x1e_0_c_0_0_0_0() MCGEN_EVENT_BIT_SET(ProviderName3_418DACB3DA4B47FD851803EA8A6552E9EnableBits, 0)

//
// Event write macros for ProviderSym3_EVENT_0x1e_0_c_0_0_0_0
//
#define EventWriteProviderSym3_EVENT_0x1e_0_c_0_0_0_0() \
        MCGEN_EVENT_ENABLED(ProviderSym3_EVENT_0x1e_0_c_0_0_0_0) \
        ? McTemplateU0(&ProviderSym3_Context, &ProviderSym3_EVENT_0x1e_0_c_0_0_0_0) : 0
#define EventWriteProviderSym3_EVENT_0x1e_0_c_0_0_0_0_AssumeEnabled() \
        McTemplateU0(&ProviderSym3_Context, &ProviderSym3_EVENT_0x1e_0_c_0_0_0_0)

#endif // MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//
// MCGEN_DISABLE_PROVIDER_CODE_GENERATION macro:
// Define this macro to have the compiler skip the generated functions in this
// header.
//
#ifndef MCGEN_DISABLE_PROVIDER_CODE_GENERATION

//
// Template Functions
//
//
//Template from manifest : (null)
//
#ifndef McTemplateU0_def
#define McTemplateU0_def
ETW_INLINE
ULONG
McTemplateU0(
    _In_ PMCGEN_TRACE_CONTEXT Context,
    _In_ PCEVENT_DESCRIPTOR Descriptor
    )
{
#define McTemplateU0_ARGCOUNT 0

    EVENT_DATA_DESCRIPTOR EventData[McTemplateU0_ARGCOUNT + 1];

    return McGenEventWrite(Context, Descriptor, NULL, McTemplateU0_ARGCOUNT + 1, EventData);
}
#endif // McTemplateU0_def

#endif // MCGEN_DISABLE_PROVIDER_CODE_GENERATION

#if defined(__cplusplus)
};
#endif

#define MSG_provider_1                       0x90000001L
#define MSG_provider_2                       0x91000001L
#define MSG_provider_3                       0x92000001L
