//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManifestCompiler.Build.Tasks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EventManifestCompiler.Build.Tasks.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required file &quot;{0}&quot; is missing..
        /// </summary>
        internal static string Error_MissingFile {
            get {
                return ResourceManager.GetString("Error_MissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{1}&quot; task received an invalid value for the &quot;{0}&quot; parameter..
        /// </summary>
        internal static string General_InvalidValue {
            get {
                return ResourceManager.GetString("General_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking command:.
        /// </summary>
        internal static string Native_TrackingCommandMessage {
            get {
                return ResourceManager.GetString("Native_TrackingCommandMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forcing rebuild of all source files due to a change in the command line since the last build..
        /// </summary>
        internal static string TrackedToolTask_RebuildingAllSourcesCommandLineChanged {
            get {
                return ResourceManager.GetString("TrackedToolTask_RebuildingAllSourcesCommandLineChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forcing a rebuild of all sources due to an error with the tracking logs. {0}.
        /// </summary>
        internal static string TrackedToolTask_RebuildingDueToInvalidTLog {
            get {
                return ResourceManager.GetString("TrackedToolTask_RebuildingDueToInvalidTLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forcing a rebuild of all source files due to the contents of &quot;{0}&quot; being invalid..
        /// </summary>
        internal static string TrackedToolTask_RebuildingDueToInvalidTLogContents {
            get {
                return ResourceManager.GetString("TrackedToolTask_RebuildingDueToInvalidTLogContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forcing rebuild of all source files due to missing command TLog &quot;{0}&quot;..
        /// </summary>
        internal static string TrackedToolTask_RebuildingNoCommandTLog {
            get {
                return ResourceManager.GetString("TrackedToolTask_RebuildingNoCommandTLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forcing rebuild of source file &quot;{0}&quot; due to a change in the command line since the last build..
        /// </summary>
        internal static string TrackedToolTask_RebuildingSourceCommandLineChanged {
            get {
                return ResourceManager.GetString("TrackedToolTask_RebuildingSourceCommandLineChanged", resourceCulture);
            }
        }
    }
}
