//-----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ManifestToCode tool.
//     Tool Version: 14.0.50929.2
// </auto-generated>
//-----------------------------------------------------------------------------

using System;

namespace EventTraceKit.VsExtension
{
    public static class ImageIds
    {
        public static readonly Guid EtkImagesGuid = new Guid("{14a2454c-0fc5-4939-a9a7-5bc089416c70}");

        public const int TraceLog = 1;
    }
}
