//-----------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ManifestToCode tool.
//     Tool Version: 14.0.50929.2
// </auto-generated>
//-----------------------------------------------------------------------------

using Microsoft.VisualStudio.Imaging.Interop;

namespace EventTraceKit.VsExtension
{
    public static class KnownImageMonikers
    {
        public static ImageMoniker TraceLog { get { return new ImageMoniker { Guid = ImageIds.EtkImagesGuid, Id = ImageIds.TraceLog }; } }
    }
}
